### ISSUE TITLE
Setup a docker based dev environment

### ISSUE THREAD

**Issue by rushab-shah** [CSCI-GA-2820-SP23-003/recommendations#10]
**As a** developer
**I need** to setup a containerized dev environment  
**So that** I can develop and test features locally
   
 ### Details and Assumptions
 * Need to pull the repository locally 
 * Need to test the Docker file and make necessary changes
 * Need to create a local db setup to test changes
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a git repo available for recommendation service
 When I pull the code locally and run the required commands
 Then there should be available a Dev ready environment for development and testing
```

**Comment by yjlo123** [comment]
The dev environment may include a local MySQL setup for testing

**Comment by rushab-shah** [comment]
Removing from Sprint and closing as this story is already implemented.
