### ISSUE TITLE
Like/Dislike function for a recommendation

### ISSUE THREAD

**Issue by hzhao2349** [CSCI-GA-2820-SP23-003/recommendations#11]
**As a** User
**I need** Like/Dislike buttons for a recommendation
**So that** further recommendations can be more accurate

### Assumptions
- Products in a recommendation list are ordered with priority
- Like/Dislike buttons would increase/decrease the priority for that product

### Acceptance Criteria
 ```gherkin
Given A product in the list is Liked/Disliked and its priority has been changed
When The User refreshes the page
Then The list order would be different
 ```

**Comment by yjlo123** [comment]
We may need an additional DB table to store the like/dislike information
