### ISSUE TITLE
Different types for recommendations

### ISSUE THREAD

**Issue by hzhao2349** [CSCI-GA-2820-SP23-003/recommendations#12]
**As a** User
**I need** separate lists for recommendations
**So that** I can have a clearer view

### Assumptions
- Recommendations have different types like cross-sell, up-sell, accessory, etc.
- When presenting recommendations, same-type products would be in the same list

### Acceptance Criteria
 ```gherkin
Given The recommendations are labeled
When A User calls recommendation
Then Several lists would be presented, each contains the same type of recommendations
```

**Comment by yjlo123** [comment]
This is used when the type param is not provided when calling the listing API
