### ISSUE TITLE
API to list all the recommendations

### ISSUE THREAD

**Issue by 22moni6** [CSCI-GA-2820-SP23-003/recommendations#13]
**As a** User
**I need** way to list all the recommendations   
**So that** we can fetch all the recommendations when a product is being searched
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the REST API for listing all the recommendations is available
When I make a GET call to the '/recommendations/` API
Then all the recommendations will be listed
```

**Comment by rushab-shah** [comment]
Can we assign this to someone?
