### ISSUE TITLE
Return proper error messages for the "update" API

### ISSUE THREAD

**Issue by yjlo123** [CSCI-GA-2820-SP23-003/recommendations#24]
**Describe the bug**
When the params for the update API is invalid, there is a server error

**To Reproduce**
1. Call the update API with an invalid param, e.g. missing "type" param
2. Will get a server error message

**Expected behavior**
A proper error message describing why the request failed

**Observed behavior**
Internal server error message, the stack printed in the server log

**Comment by rushab-shah** [comment]
I think using the deserialize method has fixed this. Need to confirm.
