### ISSUE TITLE
Filtering Recommendation list by like

### ISSUE THREAD

**Issue by yjlo123** [CSCI-GA-2820-SP23-003/recommendations#54]
**As a** user
**I need** to filter all the recommendations by like 
**So that** I can view those I am interested in.
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by rushab-shah** [comment]
Need to update description with API signature.
