### ISSUE TITLE
Recommendation ratings for sorting the recommendation list

### ISSUE THREAD

**Issue by yjlo123** [CSCI-GA-2820-SP23-003/recommendations#6]
**As a** User  
**I need** to know the rating for each recommended product for a given product  
**So that** I can present the recommendation list in a sorted order base on the ratings  
   
 ### Details and Assumptions
 * The database table has the dedicated field to store the rating information
 * Ratings range from 1 to 100 in integer
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the API for getting recommendation list is available
 When I call the `GET /recommendation` API
 Then the response contains the rating information
```

**Comment by 22moni6** [comment]
Can you explain more about where this feature would be used in the real-time scenario?
