### ISSUE TITLE
Ability to show a specific recommendation

### ISSUE THREAD

**Issue by rushab-shah** [CSCI-GA-2820-SP23-003/recommendations#9]
**As a** User
**I need** to be able to see a specific recommendation
**So that** I can take a detailed view at a specific recommendation
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the REST API to show a recommendation is available
 When I make a GET call to /recommendations/<recommendation_id>
 Then the specific recommendation is listed
```

**Comment by yjlo123** [comment]
Different from the listing API, this API can return more details about Product A and Product B.
